spring:
  application:
    name: "Stats Dna"
  data:
    neo4j:
      database: ${NEO4J_DATABASE:stats}
  neo4j:
    #uri: ${NEO4J_URI:neo4j+s://demo.neo4jlabs.com}
#    authentication:
#      username: ${NEO4J_USER}
#      password: ${NEO4J_PASSWORD}
server:
  port: ${PORT:8080}

logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher: trace